# Generated by Django 2.0.7 on 2019-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191026_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lesson_id',
            field=models.IntegerField(default=41),
            preserve_default=False,
        ),
    ]
