# Generated by Django 2.0.7 on 2019-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
