# Generated by Django 2.0.7 on 2019-10-21 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('town_or_city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=11)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffuser.ParentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('town_or_city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=11)),
                ('pay_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
