# Generated by Django 2.0.7 on 2019-10-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='price',
        ),
    ]
