# Generated by Django 2.0.7 on 2019-10-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0002_remove_studentsession_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='price_per_session',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=4),
            preserve_default=False,
        ),
    ]
