# Generated by Django 2.0.7 on 2019-10-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0003_tutorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('start_date', models.DateField()),
                ('duration', models.DurationField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffuser.TutorProfile')),
            ],
        ),
    ]
