# Generated by Django 2.0.7 on 2019-10-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0004_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='start_date',
            new_name='date',
        ),
    ]
