# Generated by Django 2.0.7 on 2019-10-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffuser', '0005_auto_20191017_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='TutorSession',
        ),
    ]
