# Generated by Django 2.0.7 on 2019-10-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_name', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('town_or_city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=11)),
            ],
        ),
    ]
