# Generated by Django 2.0.7 on 2019-10-23 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminuser.Centre')),
            ],
        ),
    ]
