# Generated by Django 2.0.7 on 2019-10-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffuser', '0004_auto_20191020_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('attending', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffuser.TutorProfile')),
            ],
        ),
        migrations.AddField(
            model_name='studentsession',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='lessons.TutorSession'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffuser.Student'),
        ),
    ]
