# Generated by Django 2.0.7 on 2019-10-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='paid',
        ),
    ]
