# Generated by Django 2.0.7 on 2019-10-24 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminuser.Centre'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='earning',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
